# Generated by Django 5.1.15 on 2026-10-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("job", "Job"),
                            ("internship", "Internship"),
                            ("scholarship", "Scholarship"),
                            ("course", "Course"),
                            ("certification", "Certification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(max_length=120)),
                ("url", models.URLField()),
                ("location", models.CharField(default="Kenya", max_length=120)),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "source_note",
                    models.CharField(
                        default="Sample opportunity for demonstration", max_length=180
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="opportunities", to="content.skill"
                    ),
                ),
            ],
        ),
    ]
