# Generated by Django 5.1.15 on 2026-10-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=160)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("sender", models.CharField(default="console", max_length=30)),
            ],
        ),
    ]
