# Generated by Django 5.1.15 on 2026-10-01 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagement", "0001_initial"),
        ("learners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminderlog",
            name="learner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="learners.learnerprofile",
            ),
        ),
    ]
