# Generated by Django 5.1.15 on 2026-10-01 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("url", models.URLField(unique=True)),
                ("credibility_note", models.TextField()),
                ("language", models.CharField(default="en", max_length=8)),
                ("active", models.BooleanField(default=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("url", models.URLField(unique=True)),
                ("summary", models.TextField(blank=True)),
                ("published_at", models.DateTimeField()),
                ("language", models.CharField(default="en", max_length=8)),
                ("estimated_minutes", models.PositiveSmallIntegerField(default=10)),
                ("is_low_data", models.BooleanField(default=True)),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="items", to="content.skill"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="content.source",
                    ),
                ),
            ],
        ),
    ]
