# Generated by Django 5.1.15 on 2026-10-08 16:23

from django.db import migrations, models
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit


def normalize_link(value):
    parsed = urlsplit((value or "").strip())
    original_scheme = parsed.scheme.lower()
    scheme = original_scheme
    if scheme == "http":
        scheme = "https"
    host = (parsed.hostname or "").lower()
    port = parsed.port
    if port and not (
        (original_scheme == "http" and port == 80)
        or (original_scheme == "https" and port == 443)
    ):
        host = f"{host}:{parsed.port}"
    path = parsed.path.rstrip("/") or "/"
    query = urlencode(
        [
            (key, item)
            for key, item in parse_qsl(parsed.query, keep_blank_values=True)
            if not key.lower().startswith("utm_")
        ],
        doseq=True,
    )
    return urlunsplit((scheme, host, path, query, ""))


def backfill_normalized_links(apps, schema_editor):
    Item = apps.get_model("content", "Item")
    alias = schema_editor.connection.alias
    seen_links = set()
    # Lowest id keeps the normalized link; later colliding rows remain NULL.
    for item in Item.objects.using(alias).order_by("pk").iterator():
        try:
            normalized_link = normalize_link(item.url)
        except ValueError:
            normalized_link = None
        if normalized_link is None:
            item.normalized_link = None
        elif normalized_link in seen_links:
            item.normalized_link = None
        else:
            item.normalized_link = normalized_link
            seen_links.add(normalized_link)
        item.save(update_fields=["normalized_link"])


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="date_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("published", "Published"),
                    ("updated", "Updated"),
                    ("fetched", "Fetched"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="guid",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=1000
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="normalized_link",
            field=models.CharField(blank=True, max_length=2048, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="item",
            name="pathway_keys",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="item",
            name="word_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="attribution",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="source",
            name="etag",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="source",
            name="last_modified",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="source",
            name="latest_item_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="rights",
            field=models.CharField(default="not stated", max_length=80),
        ),
        migrations.RunPython(backfill_normalized_links, migrations.RunPython.noop),
    ]
