# Generated by Django 5.1.15 on 2026-10-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_item_date_source_item_fetched_at_item_guid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="level",
            field=models.CharField(default="mixed", max_length=20),
        ),
    ]
