# Generated by Django 5.1.15 on 2026-10-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(default="Learner", max_length=80)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("sw", "Kiswahili")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("reminder_opt_in", models.BooleanField(default=False)),
                (
                    "reminder_frequency",
                    models.CharField(default="weekly", max_length=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
