# Generated by Django 5.1.15 on 2026-10-01 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learners", "0001_initial"),
        ("pathways", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprofile",
            name="chosen_pathway",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learners",
                to="pathways.pathway",
            ),
        ),
    ]
