SKILL_KEYWORDS = {
    "Spreadsheets": ("spreadsheet", "excel", "google sheets"),
    "SQL": ("sql", "database", "query"),
    "Data Visualisation": (
        "data visualization",
        "data visualisation",
        "visualization",
        "visualisation",
        "chart",
    ),
    "Statistics": ("statistics", "statistical", "data analysis", "data analyst"),
    "HTML": ("html", "semantic markup"),
    "CSS": ("css", "styling", "web layout"),
    "JavaScript": ("javascript", "react", "frontend", "front-end"),
    "Accessibility": ("accessibility", "accessible", "wcag"),
    "Git": ("git", "github", "version control"),
    "Python": ("python",),
    "API Development": (
        "api development",
        "rest api",
        "api endpoint",
        "api integration",
        "api design",
        "building an api",
        "build an api",
    ),
    "Testing": (
        "testing",
        "test-driven development",
        "unit testing",
        "automated testing",
        "pytest",
    ),
    "Content Strategy": ("content strategy", "content planning", "copywriting"),
    "Social Media": ("social media", "social platform"),
    "SEO": ("seo", "search engine optimization", "search engine optimisation"),
    "Marketing Analytics": (
        "marketing analytics",
        "campaign analytics",
        "campaign metrics",
    ),
}
