# Generated by Django 5.1.15 on 2026-10-01 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        ("learners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pathway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("target_outcome", models.CharField(max_length=160)),
                ("locale", models.CharField(default="KE", max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="PathwaySkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "pathway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="pathways.pathway",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="content.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("pathway", "order"), ("pathway", "skill")},
            },
        ),
        migrations.AddField(
            model_name="pathway",
            name="skills",
            field=models.ManyToManyField(
                related_name="pathways",
                through="pathways.PathwaySkill",
                to="content.skill",
            ),
        ),
        migrations.CreateModel(
            name="Checkpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("criteria", models.TextField()),
                ("unlocks_text", models.TextField()),
                ("quiz_json", models.JSONField(default=list)),
                (
                    "pathway_skill",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoint",
                        to="pathways.pathwayskill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckpointRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("done", "Done"), ("skipped", "Skipped")],
                        max_length=12,
                    ),
                ),
                ("self_attested", models.BooleanField(default=False)),
                ("quiz_answers", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="pathways.checkpoint",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoint_records",
                        to="learners.learnerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("learner", "checkpoint")},
            },
        ),
        migrations.CreateModel(
            name="ItemRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("done_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.item"
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_records",
                        to="learners.learnerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("learner", "item")},
            },
        ),
    ]
